# Introduction to Scikit-Learn (sklearn)

This notebook demonstrates some of the most useful functions of the
beautiful Scikit-Learn library.

What we're going to cover:

0. An end-to-end Scikit-Learn workflow
1. Getting the data ready
2. Choose the right estimator (model) / algorithm for our problems
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and load a trained model
7. Putting it all together

## 0. An end-to-end Scikit-Learn workflow

In [1]:
# 1. Get the data ready
import pandas as pd
import numpy as np
import sklearn

heart_disease = pd.read_csv('./data/heart-disease.csv')
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [2]:
# Create `X` (the "feature matrix")
# AKA data or feature variables
X = heart_disease.drop('target', axis=1)
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [3]:
# Create the y (AKA labels or label matrix)
y = heart_disease['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

## 2. Choose the right model and hyperparameters

In [4]:
# Remember, "hyperparameters" are like "dials" we can use to (fine) tune our model
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

## 3. Fit the model to the training data

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
clf.fit(X_train, y_train);

In [7]:
# Make a (faulty) prediction (using **incorrectly shaped** data)
try:
    y_broken_label = clf.predict(np.array([0, 2, 3, 4]))
except Exception as e:
    print(f'Exception: {type(e).__name__}: {e}')

Exception: ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [8]:
# Make a (correct) prediction (using **correctly shaped** data)
# Note: we are still on step 3 or our workflow
y_label = clf.predict(X_test)

In [9]:
y_preds = clf.predict(X_test)
y_preds

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1])

In [10]:
y_test

112    1
21     1
111    1
219    0
162    1
      ..
90     1
125    1
183    0
209    0
147    1
Name: target, Length: 61, dtype: int64

## 4. Evaluate the model on the training data ...

In [11]:
clf.score(X_train, y_train)

1.0

In [12]:
# ... and on the test data
clf.score(X_test, y_test)

0.8688524590163934

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))  # clf.predict(X_test)

              precision    recall  f1-score   support

           0       0.86      0.86      0.86        28
           1       0.88      0.88      0.88        33

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.87      0.87      0.87        61

See the article, [Understanding a Classification Report](https://medium.com/@kohlishivam5522/understanding-a-classification-report-for-your-machine-learning-model-88815e2ce397),
for an explanation of this report.

In [14]:
# Calculate the "confusion matrix" for test and predicted values
confusion_matrix(y_test, y_preds)

array([[24,  4],
       [ 4, 29]])

In [15]:
accuracy_score(y_test, y_preds)

0.8688524590163934

## 5. Improve a model

In [16]:
# - Generate a one-time 128-bit secret for the seed.
import secrets

seed = secrets.randbits(128)
seed

321261893486832517836196070964890492469

In [17]:
# **Copy and paste** this value as the **hard-coded** random number
# generator seed
rng = np.random.default_rng(seed=77708057215789171477656921825058000355)

In [18]:
# Try different amount of `n_estimators`
for i in range(10, 100, 10):
    print(f'Trying model with {i} estimators...')
    # I use the `default_rng` with a specified seed to generate reproducible results.
    # The maximum integer I want is the largest unsigned 32-bit integer. (This value
    # is the largest value compatible with the argument to `rng.integers`.)
    clf = RandomForestClassifier(
        n_estimators=i,
        random_state=rng.integers(np.iinfo(np.uint32).max)).fit(X_train, y_train)
    print(f'Model accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%')
    print('')  # simply to separate runs

Trying model with 10 estimators...
Model accuracy on test set: 85.25%

Trying model with 20 estimators...
Model accuracy on test set: 86.89%

Trying model with 30 estimators...
Model accuracy on test set: 86.89%

Trying model with 40 estimators...
Model accuracy on test set: 81.97%

Trying model with 50 estimators...
Model accuracy on test set: 86.89%

Trying model with 60 estimators...
Model accuracy on test set: 90.16%

Trying model with 70 estimators...
Model accuracy on test set: 88.52%

Trying model with 80 estimators...
Model accuracy on test set: 88.52%

Trying model with 90 estimators...
Model accuracy on test set: 86.89%

The maximum accuracy of the test set, 91.80%, occurs with 50 estimators.

Consequently, we can **improve** our model by using 50 estimators.

## 6. Save and load a trained model

In [19]:
# We can save a model using `pickle`.
import pickle

In [20]:
# The video calls `pickle.dump(clf, open('random_forest_model.pkl', 'wb'))`.
# This call results in a type warning similar to
# "Expected SupportsWrite but got BinaryIO".
# This situation is resolved by using `with` below.

with open('./random_forest_model_1.pkl', 'wb') as f:
    pickle.dump(clf, f)

In [21]:
# What happens if we try to import the saved model.
with open('./random_forest_model_1.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

In [22]:
loaded_model.score(X_test, y_test)

0.8688524590163934

This result is the **same** as the last model we tried (90 estimators). **Hooray!**

In [23]:
# Let's "listify" the contents
what_were_covering = [
    '0. An end-to-end Scikit-Learn workflow',
    '1. Getting the data ready',
    '2. Choose the right estimator/algorithm/model for your problem',
    '3. Fitting your chosen machine learning model to data and using it to make a prediction',
    '4. Evaluating a machine learning model',
    '5. Improving predictions through experimentation (hyperparameter tuning)',
    '6. Saving and loading a pre-trained model',
    '7. Putting it all together in a pipeline',
]

In [24]:
what_were_covering

['0. An end-to-end Scikit-Learn workflow',
 '1. Getting the data ready',
 '2. Choose the right estimator/algorithm/model for your problem',
 '3. Fitting your chosen machine learning model to data and using it to make a prediction',
 '4. Evaluating a machine learning model',
 '5. Improving predictions through experimentation (hyperparameter tuning)',
 '6. Saving and loading a pre-trained model',
 '7. Putting it all together in a pipeline']

In [25]:
# Standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

## 1. Getting our data ready to be used with machine learning

Three main tasks to complete:

1. Split the data into features and labels (usually `X` and `y`)
2. Filling (AKA imputing) or disregarding missing values
3. Converting non-numerical values to numerical values (also called "feature encoding")

In [26]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [27]:
# The last column is our data to be predicted so we drop it
# Remember that `axis=1` is the **column** axis
# (`axis=0` is the **row** axis)
X = heart_disease.drop('target', axis=1)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [28]:
y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [29]:
# Split the features and labels into training and test splits
# We reserve 20% of our data for testing. This amount is "negotiable" for
# different problems.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [30]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [31]:
X.shape

(303, 13)

In [32]:
len(heart_disease)

303

In [33]:
len(heart_disease) * 0.8

242.4

In [34]:
242 + 61

303

In [35]:
len(heart_disease)

303

## 1.1 Make sure all data is **numerical**

In [36]:
car_sales = pd.read_csv('./data/car-sales-extended.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [37]:
car_sales['Doors'].value_counts()

Doors
4    856
5     79
3     65
Name: count, dtype: int64

Notice that `car_sales['Doors']` is **both** numeric **and** categorical.

It is numeric because its values are integers. But it is categorical
because it's (mathematical) range is only a small subset of integers.

As a consequence of the small subset of values, we will treat this column
as a **categorical** column (see our encoding code later).

In [38]:
len(car_sales)

1000

In [39]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [40]:
# Split into `X` and `y`
X = car_sales.drop('Price', axis=1)
y = car_sales['Price']

# Split into training and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [41]:
# Build machine learning model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor() ## Create our model
try:
    model.fit(X_train, y_train) ## Fit our model
    model.score(X_test, y_test) ## Score our model
except Exception as e:
    print(f'Exception: {type(e).__name__}: {e}')
# Score

Exception: ValueError: could not convert string to float: 'Honda'

Remember, we **must** convert strings (objects) to **numbers**

In [42]:
# Turn the (object) categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Identify features by **column names**
categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',  ## Name our transform
                                  one_hot,  ## The specific transformer
                                  categorical_features)],  ## Applies **only** to `categorical_features`
                                remainder='passthrough')  ## Pass all other columns **unchanged**
transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [43]:
pd.DataFrame(transformed_X)

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [44]:
# An alternative to one-hot encoding
dummies = pd.get_dummies(car_sales[['Make', 'Colour', 'Doors']])
dummies

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,4,False,True,False,False,False,False,False,False,True
1,5,True,False,False,False,False,True,False,False,False
2,4,False,True,False,False,False,False,False,False,True
3,4,False,False,False,True,False,False,False,False,True
4,3,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,4,False,False,False,True,True,False,False,False,False
996,3,False,False,True,False,False,False,False,False,True
997,4,False,False,True,False,False,True,False,False,False
998,4,False,True,False,False,False,False,False,False,True
999,4,False,False,False,True,False,True,False,False,False

Now that our data is all numeric (zeros and ones), let's refit the model

In [45]:
# Let's try to convert our data to numbers
# Remember our first step in Getting Your Data Ready.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot', one_hot, categorical_features)],
                                remainder='passthrough')

transformed_X = transformer.fit_transform(car_sales)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

In [46]:
# We start with a well-known seed to our random number generator.
# Note: we've already done this, but we are doing it again to
# "train our fingers."
import secrets

seed = secrets.randbits(128)
seed

132274868247737383409059246353066465765

In [47]:
# **MANUALLY** (re-)seed the `np.random.default_rng` with the
# seed from the previous cell.
rng = np.random.default_rng(seed=22232115356560702892793270496072236204)

In [48]:
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

model.fit(X_train, y_train)

RandomForestRegressor()

In [49]:
model.score(X_test, y_test)

0.9991928819601973

In [50]:
print(sklearn.__version__)

1.5.1

## 1.2 What if I find **missing** data?

1. Fill them with some value (AKA imputation)
2. Remove the samples with missing data altogether

Neither of these techniques is "perfect" or "recommended"
- Replacing "missing" data might introduce bias or "throw away" "significant" information
- Removing samples completely results in less total data to use

In [51]:
# Import car sales with missing data
car_sales_missing = pd.read_csv('./data/car-sales-extended-missing-data.csv')
car_sales_missing.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [52]:
# Extract `X` and `y` (features and values)
X = car_sales_missing.drop('Price', axis=1)
y = car_sales_missing['Price']

In [53]:
# Calling `.sum()` takes advantage of Python "coercion" of Boolean types
# That is, True is converted to 1 when summing and False is converted to 0.
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [54]:
# Let's try to convert our data to numbers
# Remember our first step in Getting Your Data Ready.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot', one_hot, categorical_features)],
                                remainder='passthrough')

transformed_X = transformer.fit_transform(car_sales)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

At this point in the video, Python reports an exception:
"ValueError: Input contains NaN"

Because I'm using `sklearn` version 1.5.x, I **do not** see this error.

But I'll pretend like I do.

In [55]:
car_sales_missing

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [56]:
car_sales_missing['Doors'].value_counts()

Doors
4.0    811
5.0     75
3.0     64
Name: count, dtype: int64

In [57]:
car_sales_missing['Doors'].mode()

0    4.0
Name: Doors, dtype: float64

#### Option 1: Fill missing data with `pandas`

In [58]:
# Fill the "Make" column
car_sales_missing['Make'] = car_sales_missing['Make'].fillna('missing')

# Fill the "Colour" column
car_sales_missing['Colour'] = car_sales_missing['Colour'].fillna('missing')

# Fill the "Odometer (KM)" column
car_sales_missing['Odometer (KM)'] = car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean())

# Fill the "Doors" column
# A little tricky because this column is actually a **categorical** column.
# Because the (overwhelming) majority of cars have 4 doors, we will
# replace all missing values in the 'Doors' column with the value 4.
# (Because 4 is the most common value, we could replace the hard-coded
# value of 4 with `car_sales_missing['Doors'].mode()`
car_sales_missing['Doors'] = car_sales_missing['Doors'].fillna(4)

In [59]:
# Check our `DataFrame` again
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [60]:
# Because 'Price' is our value column, we **do not** want to replace
# missing values with another value. Instead, we will **remove** all
# rows that are missing a value in the 'Price' column.
car_sales_missing = car_sales_missing.dropna(subset=['Price'])

In [61]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [62]:
len(car_sales_missing)

950

In [63]:
# Remember, one must **always** split data into `X` and `y`
# (features and labels) after **changing** the data.
X = car_sales_missing.drop('Price', axis=1)
y = car_sales_missing['Price']

In [64]:
# Let's try to convert our data to numbers
# Remember our first step in Getting Your Data Ready.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot', one_hot, categorical_features)],
                                remainder='passthrough')

transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

### Option 2. Fill missing values with Scikit-Learn

In [65]:
# Read data (as usual)
car_sales_missing = pd.read_csv('./data/car-sales-extended-missing-data.csv')
car_sales_missing.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [66]:
# Check for missing data
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [67]:
# Remove rows **without** labels
car_sales_missing = car_sales_missing.dropna(subset=['Price'])
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [68]:
# Split into features and labels
X = car_sales_missing.drop('Price', axis=1)
y = car_sales_missing['Price']

In [69]:
X.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [70]:
# Fill missing values from Scikit-LearnA
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with 'missing' and numerical values with `mean()`
categorical_imputer = SimpleImputer(strategy='constant', fill_value='missing')
door_imputer = SimpleImputer(strategy='constant', fill_value=4)
numeric_imputer = SimpleImputer(strategy='mean')

# Define columns
categorical_features = ['Make', 'Colour']
door_feature = ['Doors']  ## Because 'Doors' column is a special case
numeric_features = ['Odometer (KM)']

# Create an imputer (that is, something the fills missing data)
imputer = ColumnTransformer([
    ('categorical_features', categorical_imputer, categorical_features),
    ('door_feature', door_imputer, door_feature),
    ('numeric_features', numeric_imputer, numeric_features),
])

# (Finally) Transform the features
filled_X = imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [71]:
# Check our code as we have done previously (using `isna().sum()`
car_sales_missing = pd.DataFrame(filled_X,
                                 columns=['Make', 'Colour', 'Doors', 'Odometer (KM)'])
car_sales_missing

        Make Colour Doors Odometer (KM)
0      Honda  White   4.0       35431.0
1        BMW   Blue   5.0      192714.0
2      Honda  White   4.0       84714.0
3     Toyota  White   4.0      154365.0
4     Nissan   Blue   3.0      181577.0
..       ...    ...   ...           ...
945   Toyota  Black   4.0       35820.0
946  missing  White   3.0      155144.0
947   Nissan   Blue   4.0       66604.0
948    Honda  White   4.0      215883.0
949   Toyota   Blue   4.0      248360.0

[950 rows x 4 columns]

In [72]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [73]:
# Let's try to convert our data to numbers
# Remember our first step in Getting Your Data Ready.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot', one_hot, categorical_features)],
                                remainder='passthrough')

transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

Now our data is

- All numeric
- Filled (no missing values)

Let's fit a model!

In [74]:
# We start with a well-known seed to our random number generator.
# Note: we've already done this, but we are doing it again to
# "train our fingers."
import secrets

seed = secrets.randbits(128)
seed

27098596114143886705204159118176333905

In [75]:
# **MANUALLY** (re-)seed the `np.random.default_rng` with the
# seed from the previous cell.
rng = np.random.default_rng(seed=124608693003265431754472593407374562997)

In [76]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.2603427261931526

In [77]:
len(car_sales_missing), len(car_sales)

(950, 1000)

**Note**: The 50 less values in the transformed data is because we
dropped the rows (50 total) with missing values in the
transformed data.

In [78]:
what_were_covering

['0. An end-to-end Scikit-Learn workflow',
 '1. Getting the data ready',
 '2. Choose the right estimator/algorithm/model for your problem',
 '3. Fitting your chosen machine learning model to data and using it to make a prediction',
 '4. Evaluating a machine learning model',
 '5. Improving predictions through experimentation (hyperparameter tuning)',
 '6. Saving and loading a pre-trained model',
 '7. Putting it all together in a pipeline']

## 2. Choosing the right estimator/algorithm/model for your problem

Some things to note:

- The package, `sklearn`, refers to machine learning models and
  algorithms as _estimators_
  - A _classifier_ is one type of estimator
  - A _regressor_ is another type of estimator
- Classification problem - predicting a **category**
  - For example, heart disease or not heart disease
  - Sometimes you see the term, `clf`
    - A TLA for **classifier**
    - Used as a classification estimator
- Regression problem - predicting a **number**
  - For example, the selling price of a car

If you're

- Working on a machine learning problem
- Looking to use `sklearn`
- Unsure what model you should use

Use the `sklearn` [machine learning model map](https://scikit-learn.org/stable/machine_learning_map.html)

### 2.1 Picking a machine learning model for a regression problem

Let's use the California Housing Data Set

Daniel, where are you getting these ideas from?

The `sklearn` documentation on [datasets](https://scikit-learn.org/stable/datasets.html)

- [Toy datasets](https://scikit-learn.org/stable/datasets/toy_dataset.html)
- [Real World datasets](https://scikit-learn.org/stable/datasets/real_world.html)
- [Generated datasets](https://scikit-learn.org/stable/datasets/sample_generators.html)
- [Loading other datasets](https://scikit-learn.org/stable/datasets/loading_other_datasets.html)

In [79]:
# Get the California Housing dataset
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [80]:
# Let's turn our data into a `pandas` `DataFrame`
# Remember that the **datat** is in `housing.data`
housing_df = pd.DataFrame(housing['data'],
                          columns=housing['feature_names'])
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [81]:
# We must add our target data to the data frame
housing_df[housing.target_names[0]] = housing.target
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [82]:
# Lets change the target column name to "target"
housing_df = housing_df.rename({'MedHouseVal': 'target'}, axis=1)
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [83]:
# Split data into features and targets (`X` and `y`)
X = housing_df.drop('target', axis=1)
y = housing_df['target']

In [84]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [85]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: target, Length: 20640, dtype: float64

Let's use our "full" set of steps

- Import algorithm
- Setup random seed
- Create the data

In [86]:
# Import algorithm
from sklearn import linear_model

In [87]:
# Set up repeatable random number generator part 1

# Calculate our new seed
import secrets

seed = secrets.randbits(128)
seed

242363467870714203846866362642661944578

In [88]:
# Set up repeatable random number generator part 2

# Create a random number generator with the specified seed
rng = np.random.default_rng(seed=187614292792846192168046308353096246446)

In [89]:
# Create the data
X = housing_df.drop('target', axis=1)
y = housing_df['target'] # median house price in $100k

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate and fit the model on the **training** set
model = linear_model.Ridge(alpha=0.5)
model.fit(X_train, y_train)

# Check the score of the model on the test set
model.score(X_test, y_test)

0.5986782681772989

What if `Ridge` did not work or the score did not fit our needs?

Well, we could always try a different model....

Let's try an "ensemble model"!

An "ensemble" is a combination of smaller models to try to make
better predictions than just a single model.

The ensemble models for `sklearn` can be found [here](https://scikit-learn.org/stable/modules/ensemble.html)

In [90]:
# Import the `RandomForestRegressor` model class from the ensemble module
from sklearn.ensemble import RandomForestRegressor

In [91]:
# Calculate our new random seed
import secrets

seed = secrets.randbits(128)
seed

20717103177106046274233922339781200557

In [92]:
# Use this seed to seed a "new" random number generator
rng = np.random.default_rng(seed=20717103177106046274233922339781200557)

In [94]:
# Create the data
X = housing_df.drop('target', axis=1)
y = housing_df['target']

# Split into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create, fit, and score our random forest model
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8097940439078242

# 2.2 Picking a machine learning model for a classification problem